name: "StreamLimit"
guid: "d98fbe02-daf3-4c09-a832-4b4e1d07326c"
version: "1.1.0.0"
targetAbi: "10.10.5.0"
framework: "net8.0"
overview: "Stream Limiter"
description: "Limit the number of streams a user can have."
category: "General"
owner: "JellyboxAD"
timestamp: "2025-09-06T20:15:00Z"
artifacts:
  - "Jellyfin.Plugin.StreamLimit.dll"
changelog: |-

  ### [v1.1.0.0]
  - Added DefaultMaxStreams configuration (global default limit)
  - Limiter now falls back to default when no per-user override
  - Settings UI updated with default field and smarter overrides
  - API GetUserStreamLimit returns effective value and source

  ### [v1.0.0.1]
  - Updated controller
  - Fixed iOS error
  - Fixed configuration management

  ### [v1.0.0.0]
  - Initial version
